module.exports={
    SIGN_IN_STATUS:"signinStatus",
    FILE_ID:"fileId",
    ACCESS_TOKEN:"accessToken",
    PREVIOUS_WALLET:"previous_wallet",
    CLIENT_PRIVATEKEY :"client_privatekey",
    CLIENT_PUBLICKEY:"client_publickey",
    CLIENT_SALT:"client_salt",
    SERVER_PUBLICKEY:"server_publickey",
    LIGHT_TOKEN:"light_token",
    EXTERNAL_DB_REF_ID :"externalDatabaseRefId",
    PREVIOUS_RECOVER_WALLET : "previous_recover_wallet",
    WALLETBACKUPED :"wallet_backuped",
    BACKUPEDARGEE :"backuped_agree_term_condition",
    LEGAL_DETAIL:'legal_detail',
    DISPLAY_CHAIN_LIST:'DisplayChainList',
    EYE_ON_OFF_STATUS:'eyeOnOffStatus',
    CURRENT_USER_EMAIL:'current_user_email',
    CURRENT_USER_PASSCODE:'current_user_passcode',
    PASSCODE_MODE:'passcode_mode',
    BIOMETRICS_MODE:'biometrics_mode',
    TOST_MESSAGE :'tost_message_callback',
    BIOMETRICS_DEVICE_HAS_SUPPORTED:'biometrics_device_has_supporte',
    UNLOCK_WITH_BIOMETRICS_ENABLE:'Unlock with biometric successfully enabled',
    UNLOCK_WITH_BIOMETRICS_DISABLE:'Unlock with biometric successfully disabled',
    BACKGROUND_DATE:'background_date',
    LOCK_LUNCH_SCREEN_PRESENT:'lock_lunch_screen_present',
    TIMER_TYPE:'timer_type',
    TIMER_TIME:'timer_time',
}
