const types = {
    SCANNED_ADDRESS : 'SCANNED_ADDRESS',
    RESET_STATE_QRCODE: 'RESET_STATE_QRCODE',
    SCANNED_ADDRESS_ERROR_STATUS: 'SCANNED_ADDRESS_ERROR_STATUS',
    SCANNED_QRCODE_ERROR_STATUS: 'SCANNED_QRCODE_ERROR_STATUS',
    CURRENT_CURRENCY: 'CURRENT_CURRENCY',
    RESET_STATE_CURRENCY: 'RESET_STATE_CURRENCY',
}

export default types